#define POST_ASSIGNMENT                  1
#define POST_CONDITION_OR                2
#define POST_CONDITION_AND               3
#define POST_NOT                         4
#define POST_CONDITION_EQ                5
#define POST_CONDITION_NEQ               6
#define POST_CONDITION_LT                7
#define POST_CONDITION_GT                8
#define POST_CONDITION_LTEQ              9
#define POST_CONDITION_GTEQ             10
#define POST_CONDITION_IS_NULL          11
#define POST_AMPERSAND                  12
#define POST_PLUS                       13
#define POST_SUBTRACT                   14
#define POST_MULTIPLY                   15
#define POST_DIVISION                   16
#define POST_MODULAR_DIVISION           17
#define POST_BEGIN                      18
#define POST_END                        19
#define POST_END_OF_FILE                20
#define POST_SEMI_COLON                 21
#define POST_EXECUTER                   22
#define POST_COMMENT_START              23
#define POST_COMMENT_END                24
#define POST_JOINCONDITION_START        25
#define POST_JOINCONDITION_SEPARATOR    26
#define POST_JOINCONDITION_END          27
#define POST_WHERECLAUSEEVALUATION_START  28
#define POST_WHERECLAUSEEVALUATION_END  29
#define POST_SQLEVALUATION_START        30
#define POST_SQLEVALUATION_END          31
#define POST_IDENTIFIER                 32
#define POST_COLON                      33
#define POST_JOIN_ANYCHARACTER          34
#define POST_PLSQL_BLOCK_ANYCHARACTER   35
#define POST_BLOCK_REFERENCE            36
#define POST_OPEN_PARANTHESIS           37
#define POST_CLOSE_PARANTHESIS          38
#define POST_CONDITION_IS_NOT_NULL      39
#define POST_CONDITION_LIKE             40
#define POST_CONDITION_NOT_LIKE         41
#define POST_PLSQL_BLOCK_BEGIN          42
#define POST_PLSQL_BLOCK_END            43
#define POST_INSERT                     44
#define POST_UPDATE                     45
#define POST_DELETE                     46
#define POST_MACRO_LINE                 47
#define POST_VARIABLE_TYPE_VARCHAR      48
#define POST_COMMA                      49
#define POST_VARIABLE_TYPE_REDIS        50
#define POST_VARIABLE_TYPE_BOOL         51
#define POST_VARIABLE_TYPE_NUMBER       52
#define POST_VARIABLE_TYPE_DATE         53
#define POST_RETURN_PREFIX              54
#define POST_WHILE                      55
#define POST_LOOP_1                     56
#define POST_LOOP_END_1                 57
#define POST_LOOP_1_LINE_CHARS          58
#define POST_CONDITION_CHAR             59
#define POST_IF                         60
#define POST_THEN                       61
#define POST_END_IF_WITH_SEMICOLON      62
#define POST_ELSE                       63
#define POST_IF_LINE                    64
#define POST_SIZEOF_PREFIX              65
#define POST_STRLEN_PREFIX              66
#define POST_SUBSTR_PREFIX              67
#define POST_CREATE_ORACLE_CONNECTION_PREFIX  68
#define POST_CREATE_MYSQL_CONNECTION_PREFIX  69
#define POST_CLOSE_REDIS_CONNECTION_PREFIX  70
#define POST_CREATE_REDIS_CONNECTION_PREFIX  71
#define POST_CREATE_POSTGRESQL_CONNECTION_PREFIX  72
#define POST_TO_JSON_PREFIX             73
#define POST_RUN_SQL_FILE_PREFIX        74
#define POST_GET_DATABASE_NAME_PREFIX   75
#define POST_GET_DATABASE_TYPE_PREFIX   76
#define POST_INSTR_PREFIX               77
#define POST_REPLACE_PREFIX             78
#define POST_PREVIOUS_RECORD_PREFIX     79
#define POST_LAST_RECORD_PREFIX         80
#define POST_FIRST_RECORD_PREFIX        81
#define POST_NEXT_RECORD_PREFIX         82
#define POST_HIDE_BLOCK_PREFIX          83
#define POST_SHOW_BLOCK_PREFIX          84
#define POST_SHOW_PAGE_PREFIX           85
#define POST_MESSAGE_PREFIX             86
#define POST_REFRESH_TREE_NODE_PREFIX   87
#define POST_REFRESH_BLOCK_PREFIX       88
#define POST_SET_DATABLOCK_PROPERTY_PREFIX  89
#define POST_SHOW_COLUMN_PREFIX         90
#define POST_HIDE_COLUMN_PREFIX         91
#define POST_DISABLE_COLUMN_PREFIX      92
#define POST_ENABLE_COLUMN_PREFIX       93
#define POST_PROMPT_PREFIX              94
#define POST_POPULATE_DATALIST_PREFIX   95
#define POST_POPULATE_TREE_PREFIX       96
#define POST_ROLLBACK_PREFIX            97
#define POST_COMMIT_PREFIX              98
#define POST_TRUE                       99
#define POST_FALSE                     100
#define POST_NULL                      101
#define POST_DML_START                 102
#define POST_DML_END                   103
#define POST_DML_CHAR                  104
#define POST_STRING_CONSTANT_START     105
#define POST_STRING_CONSTANT_END       106
#define POST_STRING_CONSTANT_APOSTROPHE 107
#define POST_STRING_CONSTANT_CHAR      108
#define POST_NUMBER_CONSTANT           109
#define POST_SESSION_ID                110
#define POST_ROW_ID                    111
#define POST_PERIOD                    112
#define POST_REDIS_STRLEN_PREFIX       113
#define POST_REDIS_APPEND_PREFIX       114
#define POST_REDIS_INCR_PREFIX         115
#define POST_REDIS_INCRBY_PREFIX       116
#define POST_REDIS_DECR_PREFIX         117
#define POST_REDIS_DECRBY_PREFIX       118
#define POST_REDIS_GET_PREFIX          119
#define POST_REDIS_DEL_PREFIX          120
#define POST_REDIS_SET_PREFIX          121
#define POST_REDIS_PING_PREFIX         122
