#pragma once

typedef enum _sql_command_type {
	SQL_COMMAND_TYPE_SELECT_NO_SCROLL,
	SQL_COMMAND_TYPE_SELECT_SCROLLABLE,
	SQL_COMMAND_TYPE_UPDATE,
	SQL_COMMAND_TYPE_INSERT,
	SQL_COMMAND_TYPE_DELETE,
	SQL_COMMAND_TYPE_PLSQL
} SQL_COMMAND_TYPE;